/* ========================================================================
 * Copyright 2014 mp.mancipe10
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 mp.mancipe10

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['controller/_championShipController','delegate/championShipDelegate'], function() {
    App.Controller.ChampionShipController = App.Controller._ChampionShipController.extend({
        language: function(){
            alert('Usted esta viendo la version en ESPAÑOL de esta pagina');
        },
        days: function(params){
            console.log(params.startDate);
            console.log(params.endDate);
            var fechaIn = (params.startDate).split('/');
            var fechaFn = (params.endDate).split('/');
            var nIn = parseInt(fechaIn[0]);
            var nFn = parseInt(fechaFn[0]);
            var difD = nFn - nIn;
            var costo = Math.pow(Math.E,(0.5*difD));
            alert('La duracion de este campeonato es de: '+ difD + ' dias y su  es de:' + costo);
        }

    });
    return App.Controller.ChampionShipController;
}); 